name: piki_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  file_picker: ^9.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.17
  http_parser: ^4.1.2
  intl: ^0.20.2
  jwt_decode: ^0.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/loading.gif
  fonts:
    - family: GoldenChesse
      fonts:
        - asset: assets/fonts/golden_chesse.otf
